# This is a basic workflow to help you get started with Actions

name: Build Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "ci-test" ]
  # pull_request:
  #   branches: [ "ci-test" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build-images:
    name: Build image for ${{ matrix.machine }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine: ['sifive_unmatched', 'allwinner_d1', 'starfive_jh7110']

    steps:
    - name: checkout workdir
      uses: actions/checkout@v3

    - name: install latest debian-ports-archive-keyring
      run: |
          wget http://ftp.debian.org/debian/pool/main/d/debian-ports-archive-keyring/debian-ports-archive-keyring_2023.02.01_all.deb
          sudo apt install ./debian-ports-archive-keyring_2023.02.01_all.deb

    - name: build image
      env:
        MACHINE: ${{ matrix.machine }}
      run: |
          sudo -E ./mkimage.sh

